// Code generated by MockGen. DO NOT EDIT.
// Source: peer.go
//
// Generated by this command:
//
//	mockgen -source=peer.go -destination=mock_peerservice_test.go -package=telegram PeerService
//

// Package telegram is a generated GoMock package.
package telegram

import (
	context "context"
	reflect "reflect"

	constant "github.com/gotd/td/constant"
	peers "github.com/gotd/td/telegram/peers"
	gomock "go.uber.org/mock/gomock"
)

// MockPeerService is a mock of PeerService interface.
type MockPeerService struct {
	ctrl     *gomock.Controller
	recorder *MockPeerServiceMockRecorder
	isgomock struct{}
}

// MockPeerServiceMockRecorder is the mock recorder for MockPeerService.
type MockPeerServiceMockRecorder struct {
	mock *MockPeerService
}

// NewMockPeerService creates a new mock instance.
func NewMockPeerService(ctrl *gomock.Controller) *MockPeerService {
	mock := &MockPeerService{ctrl: ctrl}
	mock.recorder = &MockPeerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerService) EXPECT() *MockPeerServiceMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockPeerService) Resolve(ctx context.Context, from string) (peers.Peer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, from)
	ret0, _ := ret[0].(peers.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockPeerServiceMockRecorder) Resolve(ctx, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockPeerService)(nil).Resolve), ctx, from)
}

// ResolveID mocks base method.
func (m *MockPeerService) ResolveID(ctx context.Context, ID int64) (peers.Peer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveID", ctx, ID)
	ret0, _ := ret[0].(peers.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveID indicates an expected call of ResolveID.
func (mr *MockPeerServiceMockRecorder) ResolveID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveID", reflect.TypeOf((*MockPeerService)(nil).ResolveID), ctx, ID)
}

// ResolveTDLibID mocks base method.
func (m *MockPeerService) ResolveTDLibID(ctx context.Context, ID constant.TDLibPeerID) (peers.Peer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTDLibID", ctx, ID)
	ret0, _ := ret[0].(peers.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTDLibID indicates an expected call of ResolveTDLibID.
func (mr *MockPeerServiceMockRecorder) ResolveTDLibID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTDLibID", reflect.TypeOf((*MockPeerService)(nil).ResolveTDLibID), ctx, ID)
}
