// Code generated by MockGen. DO NOT EDIT.
// Source: ../client.go
//
// Generated by this command:
//
//	mockgen -source=../client.go -destination=mock_linkedchatpeer.go -package=mocks linkedChatPeer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	constant "github.com/gotd/td/constant"
	peers "github.com/gotd/td/telegram/peers"
	tg "github.com/gotd/td/tg"
	gomock "go.uber.org/mock/gomock"
)

// MocklinkedChatPeer is a mock of linkedChatPeer interface.
type MocklinkedChatPeer struct {
	ctrl     *gomock.Controller
	recorder *MocklinkedChatPeerMockRecorder
	isgomock struct{}
}

// MocklinkedChatPeerMockRecorder is the mock recorder for MocklinkedChatPeer.
type MocklinkedChatPeerMockRecorder struct {
	mock *MocklinkedChatPeer
}

// NewMocklinkedChatPeer creates a new mock instance.
func NewMocklinkedChatPeer(ctrl *gomock.Controller) *MocklinkedChatPeer {
	mock := &MocklinkedChatPeer{ctrl: ctrl}
	mock.recorder = &MocklinkedChatPeerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklinkedChatPeer) EXPECT() *MocklinkedChatPeerMockRecorder {
	return m.recorder
}

// Fake mocks base method.
func (m *MocklinkedChatPeer) Fake() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fake")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Fake indicates an expected call of Fake.
func (mr *MocklinkedChatPeerMockRecorder) Fake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fake", reflect.TypeOf((*MocklinkedChatPeer)(nil).Fake))
}

// FullRaw mocks base method.
func (m *MocklinkedChatPeer) FullRaw(ctx context.Context) (*tg.ChannelFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullRaw", ctx)
	ret0, _ := ret[0].(*tg.ChannelFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FullRaw indicates an expected call of FullRaw.
func (mr *MocklinkedChatPeerMockRecorder) FullRaw(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullRaw", reflect.TypeOf((*MocklinkedChatPeer)(nil).FullRaw), ctx)
}

// ID mocks base method.
func (m *MocklinkedChatPeer) ID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MocklinkedChatPeerMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MocklinkedChatPeer)(nil).ID))
}

// InputPeer mocks base method.
func (m *MocklinkedChatPeer) InputPeer() tg.InputPeerClass {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputPeer")
	ret0, _ := ret[0].(tg.InputPeerClass)
	return ret0
}

// InputPeer indicates an expected call of InputPeer.
func (mr *MocklinkedChatPeerMockRecorder) InputPeer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputPeer", reflect.TypeOf((*MocklinkedChatPeer)(nil).InputPeer))
}

// IsBroadcast mocks base method.
func (m *MocklinkedChatPeer) IsBroadcast() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBroadcast")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBroadcast indicates an expected call of IsBroadcast.
func (mr *MocklinkedChatPeerMockRecorder) IsBroadcast() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBroadcast", reflect.TypeOf((*MocklinkedChatPeer)(nil).IsBroadcast))
}

// Manager mocks base method.
func (m *MocklinkedChatPeer) Manager() *peers.Manager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manager")
	ret0, _ := ret[0].(*peers.Manager)
	return ret0
}

// Manager indicates an expected call of Manager.
func (mr *MocklinkedChatPeerMockRecorder) Manager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manager", reflect.TypeOf((*MocklinkedChatPeer)(nil).Manager))
}

// Photo mocks base method.
func (m *MocklinkedChatPeer) Photo(ctx context.Context) (*tg.Photo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Photo", ctx)
	ret0, _ := ret[0].(*tg.Photo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Photo indicates an expected call of Photo.
func (mr *MocklinkedChatPeerMockRecorder) Photo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Photo", reflect.TypeOf((*MocklinkedChatPeer)(nil).Photo), ctx)
}

// Report mocks base method.
func (m *MocklinkedChatPeer) Report(ctx context.Context, reason tg.ReportReasonClass, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", ctx, reason, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MocklinkedChatPeerMockRecorder) Report(ctx, reason, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MocklinkedChatPeer)(nil).Report), ctx, reason, message)
}

// Restricted mocks base method.
func (m *MocklinkedChatPeer) Restricted() ([]tg.RestrictionReason, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restricted")
	ret0, _ := ret[0].([]tg.RestrictionReason)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Restricted indicates an expected call of Restricted.
func (mr *MocklinkedChatPeerMockRecorder) Restricted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restricted", reflect.TypeOf((*MocklinkedChatPeer)(nil).Restricted))
}

// Scam mocks base method.
func (m *MocklinkedChatPeer) Scam() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scam")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Scam indicates an expected call of Scam.
func (mr *MocklinkedChatPeerMockRecorder) Scam() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scam", reflect.TypeOf((*MocklinkedChatPeer)(nil).Scam))
}

// Sync mocks base method.
func (m *MocklinkedChatPeer) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MocklinkedChatPeerMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MocklinkedChatPeer)(nil).Sync), ctx)
}

// TDLibPeerID mocks base method.
func (m *MocklinkedChatPeer) TDLibPeerID() constant.TDLibPeerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TDLibPeerID")
	ret0, _ := ret[0].(constant.TDLibPeerID)
	return ret0
}

// TDLibPeerID indicates an expected call of TDLibPeerID.
func (mr *MocklinkedChatPeerMockRecorder) TDLibPeerID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TDLibPeerID", reflect.TypeOf((*MocklinkedChatPeer)(nil).TDLibPeerID))
}

// Username mocks base method.
func (m *MocklinkedChatPeer) Username() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Username")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Username indicates an expected call of Username.
func (mr *MocklinkedChatPeerMockRecorder) Username() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Username", reflect.TypeOf((*MocklinkedChatPeer)(nil).Username))
}

// Verified mocks base method.
func (m *MocklinkedChatPeer) Verified() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verified")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verified indicates an expected call of Verified.
func (mr *MocklinkedChatPeerMockRecorder) Verified() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verified", reflect.TypeOf((*MocklinkedChatPeer)(nil).Verified))
}

// VisibleName mocks base method.
func (m *MocklinkedChatPeer) VisibleName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VisibleName")
	ret0, _ := ret[0].(string)
	return ret0
}

// VisibleName indicates an expected call of VisibleName.
func (mr *MocklinkedChatPeerMockRecorder) VisibleName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisibleName", reflect.TypeOf((*MocklinkedChatPeer)(nil).VisibleName))
}
